[package]
name = "encrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
office = "0.8.0"
calamine = "0.24.0"
csv = "1.3.0"

[[bin]]
name = "encrypt"
path = "main.rs"
